// Copyright 2016 Petrov Kirill

#ifndef MODULES_PETROV_KIRILL_ZCALC_INCLUDE_POLYNOM_CALCULATOR_H_
#define MODULES_PETROV_KIRILL_ZCALC_INCLUDE_POLYNOM_CALCULATOR_H_

#include "tpolynom.h"



#endif // MODULES_PETROV_KIRILL_ZCALC_INCLUDE_POLYNOM_CALCULATOR_H_